name: giphy_get
description: Picker giphy EMOJI,STICKER or GIF.
version: 0.9.1
homepage: https://github.com/bazospa/giphy_get


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  cached_network_image: ^2.3.1
  property_change_notifier: ^0.2.0
  flutter_spinkit: ^4.1.2
  flutter_staggered_grid_view: ^0.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/
 
